//! Derive macro for [`fieldsmith`]. See the `fieldsmith` crate docs.
//!
//! `#[derive(Buildable)]` reads a type's fields/variants, doc comments,
//! `#[serde(...)]` renames/defaults/tag and its own `#[builder(...)]`
//! attributes, then emits:
//!
//! - `impl fieldsmith::Buildable` with `schema()` returning the runtime schema;
//! - for a struct, a `<Name>Builder` with typed setters and a checked `build()`.
//!
//! Enums reflect into a schema only — they are assembled interactively by the
//! `fieldsmith` driver, not by a generated builder.

use proc_macro::TokenStream;
use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::{
    Attribute, Data, DataEnum, DeriveInput, Expr, ExprLit, Fields, GenericArgument, Lit, LitStr,
    Meta, PathArguments, Type, parse_macro_input, punctuated::Punctuated, token::Comma,
};

/// Derive `fieldsmith::Buildable` for a named-field struct or an enum.
#[proc_macro_derive(Buildable, attributes(builder))]
pub fn derive_buildable(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

fn expand(input: DeriveInput) -> syn::Result<TokenStream2> {
    if !input.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &input.generics,
            "Buildable does not support generic types yet",
        ));
    }

    match &input.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(named) => expand_struct(&input, &named.named),
            _ => Err(syn::Error::new_spanned(
                &input.ident,
                "Buildable requires a struct with named fields",
            )),
        },
        Data::Enum(e) => expand_enum(&input, e),
        Data::Union(_) => Err(syn::Error::new_spanned(
            &input.ident,
            "Buildable cannot be derived for unions",
        )),
    }
}

// ---------------------------------------------------------------------------
// Struct expansion
// ---------------------------------------------------------------------------

fn expand_struct(
    input: &DeriveInput,
    named: &Punctuated<syn::Field, Comma>,
) -> syn::Result<TokenStream2> {
    let struct_ident = input.ident.clone();
    let struct_name = struct_ident.to_string();

    let doc = extract_doc(&input.attrs);
    let rename_all = extract_rename_all(&input.attrs)?;

    let mut fields = Vec::new();
    for f in named {
        fields.push(FieldModel::parse(f, rename_all.as_deref())?);
    }

    let schema_fields = fields.iter().map(FieldModel::schema_tokens);
    let doc_tokens = opt_str_tokens(doc.as_deref());

    let builder_ident = format_ident!("{}Builder", struct_ident);
    let builder_fields = fields.iter().map(FieldModel::builder_field);
    let builder_setters = fields.iter().map(FieldModel::builder_setter);
    let build_assigns = fields.iter().map(FieldModel::build_assign);

    Ok(quote! {
        impl ::fieldsmith::Buildable for #struct_ident {
            fn schema() -> ::fieldsmith::TypeSchema {
                ::fieldsmith::TypeSchema::Struct(::fieldsmith::StructSchema {
                    name: #struct_name,
                    doc: #doc_tokens,
                    fields: ::std::vec![ #(#schema_fields),* ],
                })
            }
        }

        #[doc = concat!("Builder for [`", stringify!(#struct_ident), "`], generated by fieldsmith.")]
        #[derive(Default)]
        #[allow(dead_code)]
        pub struct #builder_ident {
            #(#builder_fields),*
        }

        #[allow(dead_code)]
        impl #builder_ident {
            /// Create an empty builder; unset fields fall back to defaults at `build`.
            pub fn new() -> Self {
                ::core::default::Default::default()
            }

            #(#builder_setters)*

            /// Assemble the value, applying defaults and checking required fields.
            pub fn build(self) -> ::core::result::Result<#struct_ident, ::fieldsmith::BuildError> {
                ::core::result::Result::Ok(#struct_ident {
                    #(#build_assigns),*
                })
            }
        }
    })
}

// ---------------------------------------------------------------------------
// Enum expansion — schema only, no builder
// ---------------------------------------------------------------------------

fn expand_enum(input: &DeriveInput, data: &DataEnum) -> syn::Result<TokenStream2> {
    let enum_ident = input.ident.clone();
    let enum_name = enum_ident.to_string();
    let doc = extract_doc(&input.attrs);
    let doc_tokens = opt_str_tokens(doc.as_deref());
    let rename_all = extract_rename_all(&input.attrs)?;

    let tag = extract_serde_tag(&input.attrs)?;
    let tag_tokens = match &tag {
        Some(t) => {
            let l = LitStr::new(t, Span::call_site());
            quote! { ::fieldsmith::EnumTag::Internal(#l) }
        }
        None => quote! { ::fieldsmith::EnumTag::External },
    };

    let mut variant_tokens = Vec::new();
    for v in &data.variants {
        let (rename, _) = parse_field_serde(&v.attrs)?;
        let vname = match rename {
            Some(r) => r,
            None => match rename_all.as_deref() {
                Some(style) => apply_rename_all(&v.ident.to_string(), style),
                None => v.ident.to_string(),
            },
        };
        let vname_lit = LitStr::new(&vname, Span::call_site());
        let vdoc = opt_str_tokens(extract_doc(&v.attrs).as_deref());

        let vkind = match &v.fields {
            Fields::Unit => quote! { ::fieldsmith::VariantKind::Unit },
            Fields::Unnamed(u) => {
                if u.unnamed.len() != 1 {
                    return Err(syn::Error::new_spanned(
                        &v.fields,
                        "Buildable supports only single-field tuple variants (newtypes)",
                    ));
                }
                let ty = &u.unnamed.first().unwrap().ty;
                let inner = kind_tokens(ty, false);
                quote! { ::fieldsmith::VariantKind::Newtype(::std::boxed::Box::new(#inner)) }
            }
            Fields::Named(named) => {
                let mut fields = Vec::new();
                for f in &named.named {
                    fields.push(FieldModel::parse(f, None)?);
                }
                let schema_fields = fields.iter().map(FieldModel::schema_tokens);
                quote! { ::fieldsmith::VariantKind::Struct(::std::vec![ #(#schema_fields),* ]) }
            }
        };

        variant_tokens.push(quote! {
            ::fieldsmith::VariantSchema {
                name: #vname_lit,
                doc: #vdoc,
                kind: #vkind,
            }
        });
    }

    Ok(quote! {
        impl ::fieldsmith::Buildable for #enum_ident {
            fn schema() -> ::fieldsmith::TypeSchema {
                ::fieldsmith::TypeSchema::Enum(::fieldsmith::EnumSchema {
                    name: #enum_name,
                    doc: #doc_tokens,
                    tag: #tag_tokens,
                    variants: ::std::vec![ #(#variant_tokens),* ],
                })
            }
        }
    })
}

// ---------------------------------------------------------------------------
// Per-field model
// ---------------------------------------------------------------------------

/// How serde will fill a missing field, mirrored for `build()`.
enum SerdeDefault {
    /// No `#[serde(default)]`.
    None,
    /// `#[serde(default)]` — use `Default::default()`.
    Implicit,
    /// `#[serde(default = "path")]` — call `path()`.
    Path(syn::Path),
}

struct FieldModel {
    ident: syn::Ident,
    key: String,
    /// Inner type: for `Option<T>` this is `T`, otherwise the field type.
    inner_ty: Type,
    doc: Option<String>,
    optional: bool,
    default: Option<String>,
    serde_default: SerdeDefault,
    /// `#[builder(leaf)]`: force a non-primitive `FromStr` type into scalar.
    is_leaf: bool,
}

impl FieldModel {
    fn parse(field: &syn::Field, rename_all: Option<&str>) -> syn::Result<Self> {
        let ident = field
            .ident
            .clone()
            .ok_or_else(|| syn::Error::new_spanned(field, "expected a named field"))?;

        let (optional, inner_ty) = unwrap_option(&field.ty);

        let mut default = None;
        let mut doc_override = None;
        let mut is_leaf = false;
        for attr in &field.attrs {
            if attr.path().is_ident("builder") {
                parse_builder_attr(attr, &mut default, &mut doc_override, &mut is_leaf)?;
            }
        }

        let (rename, serde_default) = parse_field_serde(&field.attrs)?;
        let key = match rename {
            Some(r) => r,
            None => match rename_all {
                Some(style) => apply_rename_all(&ident.to_string(), style),
                None => ident.to_string(),
            },
        };

        let doc = doc_override.or_else(|| extract_doc(&field.attrs));

        Ok(FieldModel {
            ident,
            key,
            inner_ty,
            doc,
            optional,
            default,
            serde_default,
            is_leaf,
        })
    }

    /// A `FieldSchema { … }` literal for `schema()`.
    fn schema_tokens(&self) -> TokenStream2 {
        let key = LitStr::new(&self.key, Span::call_site());
        let doc = opt_str_tokens(self.doc.as_deref());
        let default = opt_str_tokens(self.default.as_deref());
        let optional = self.optional;
        let type_name = last_ident(&self.inner_ty).unwrap_or_else(|| "value".to_string());
        let type_name_lit = LitStr::new(&type_name, Span::call_site());
        let kind = kind_tokens(&self.inner_ty, self.is_leaf);

        quote! {
            ::fieldsmith::FieldSchema {
                key: #key,
                doc: #doc,
                optional: #optional,
                default: #default,
                type_name: #type_name_lit,
                kind: #kind,
            }
        }
    }

    /// The builder's storage field.
    fn builder_field(&self) -> TokenStream2 {
        let ident = &self.ident;
        let inner_ty = &self.inner_ty;
        if self.optional {
            quote! { #ident: ::core::option::Option<::core::option::Option<#inner_ty>> }
        } else {
            quote! { #ident: ::core::option::Option<#inner_ty> }
        }
    }

    /// A typed setter (`.field(value)`), accepting anything `Into` the type.
    fn builder_setter(&self) -> TokenStream2 {
        let ident = &self.ident;
        let inner_ty = &self.inner_ty;
        let doc = format!("Set `{}`.", self.key);
        if self.optional {
            quote! {
                #[doc = #doc]
                pub fn #ident(mut self, value: impl ::core::convert::Into<#inner_ty>) -> Self {
                    self.#ident = ::core::option::Option::Some(::core::option::Option::Some(value.into()));
                    self
                }
            }
        } else {
            quote! {
                #[doc = #doc]
                pub fn #ident(mut self, value: impl ::core::convert::Into<#inner_ty>) -> Self {
                    self.#ident = ::core::option::Option::Some(value.into());
                    self
                }
            }
        }
    }

    /// The `field: <expr>` line inside `build()`.
    fn build_assign(&self) -> TokenStream2 {
        let ident = &self.ident;
        let key = LitStr::new(&self.key, Span::call_site());
        let parse_msg = format!("fieldsmith: invalid default for `{}`", self.key);

        // A parseable default expression (via FromStr), if one is available.
        let default_expr: Option<TokenStream2> = self.default.as_deref().map(|d| {
            let lit = LitStr::new(d, Span::call_site());
            quote! { #lit.parse().expect(#parse_msg) }
        });

        if self.optional {
            // Option: default (if any) becomes Some(default); else None.
            match &default_expr {
                Some(expr) => quote! {
                    #ident: self.#ident.unwrap_or_else(|| ::core::option::Option::Some(#expr))
                },
                None => quote! {
                    #ident: self.#ident.unwrap_or(::core::option::Option::None)
                },
            }
        } else if let Some(expr) = default_expr {
            quote! { #ident: self.#ident.unwrap_or_else(|| #expr) }
        } else {
            match &self.serde_default {
                SerdeDefault::Implicit => {
                    quote! { #ident: self.#ident.unwrap_or_default() }
                }
                SerdeDefault::Path(path) => {
                    quote! { #ident: self.#ident.unwrap_or_else(|| #path()) }
                }
                SerdeDefault::None => {
                    quote! { #ident: self.#ident.ok_or(::fieldsmith::BuildError::MissingField(#key))? }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Kind classification
// ---------------------------------------------------------------------------

/// A `::fieldsmith::Kind` expression for a (non-Option) type.
///
/// `Vec<T>` → `List(Box<inner>)`; a known primitive or a `#[builder(leaf)]`
/// type → `Scalar`; anything else → `Nested`, recursing via that type's own
/// `Buildable::schema()`.
fn kind_tokens(ty: &Type, is_leaf: bool) -> TokenStream2 {
    if !is_leaf && let Some(inner) = unwrap_vec(ty) {
        let inner_kind = kind_tokens(&inner, false);
        return quote! { ::fieldsmith::Kind::List(::std::boxed::Box::new(#inner_kind)) };
    }
    match scalar_hint(ty, is_leaf) {
        Some(hint) => quote! { ::fieldsmith::Kind::Scalar(#hint) },
        None => quote! { ::fieldsmith::Kind::Nested(<#ty as ::fieldsmith::Buildable>::schema()) },
    }
}

/// The `ScalarHint` expression for a scalar type, or `None` if it is nested.
fn scalar_hint(ty: &Type, is_leaf: bool) -> Option<TokenStream2> {
    let name = last_ident(ty);
    if is_leaf {
        let n = LitStr::new(
            &name.unwrap_or_else(|| "value".to_string()),
            Span::call_site(),
        );
        return Some(quote! { ::fieldsmith::ScalarHint::Other(#n) });
    }
    match name.as_deref() {
        // `String`/`str` and the ubiquitous std path types all take a single
        // line of text and `Deserialize` from a string.
        Some("String") | Some("str") | Some("PathBuf") | Some("Path") => {
            Some(quote! { ::fieldsmith::ScalarHint::Str })
        }
        Some("bool") => Some(quote! { ::fieldsmith::ScalarHint::Bool }),
        Some("i8") | Some("i16") | Some("i32") | Some("i64") | Some("i128") | Some("isize")
        | Some("u8") | Some("u16") | Some("u32") | Some("u64") | Some("u128") | Some("usize") => {
            Some(quote! { ::fieldsmith::ScalarHint::Int })
        }
        Some("f32") | Some("f64") => Some(quote! { ::fieldsmith::ScalarHint::Float }),
        Some("char") => Some(quote! { ::fieldsmith::ScalarHint::Other("char") }),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Attribute parsing
// ---------------------------------------------------------------------------

fn parse_builder_attr(
    attr: &Attribute,
    default: &mut Option<String>,
    doc_override: &mut Option<String>,
    is_leaf: &mut bool,
) -> syn::Result<()> {
    attr.parse_nested_meta(|meta| {
        if meta.path.is_ident("default") {
            let lit: Lit = meta.value()?.parse()?;
            *default = Some(lit_to_string(&lit));
            return Ok(());
        }
        if meta.path.is_ident("doc") {
            let s: LitStr = meta.value()?.parse()?;
            *doc_override = Some(s.value().trim().to_string());
            return Ok(());
        }
        if meta.path.is_ident("leaf") {
            *is_leaf = true;
            return Ok(());
        }
        // Reserved for later phases (secret, parse_with, stdin_builder, …):
        // swallow an optional `= value` so unknown keys don't break parsing.
        if meta.input.peek(syn::Token![=]) {
            let _: Lit = meta.value()?.parse()?;
        }
        Ok(())
    })
}

/// Read `#[serde(rename = "…")]` and `#[serde(default[ = "path"])]` on a field
/// or variant. (For a variant, only `rename` is meaningful.)
fn parse_field_serde(attrs: &[Attribute]) -> syn::Result<(Option<String>, SerdeDefault)> {
    let mut rename = None;
    let mut serde_default = SerdeDefault::None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                // Support `rename = "x"`; ignore the struct-variant form.
                if meta.input.peek(syn::Token![=]) {
                    let s: LitStr = meta.value()?.parse()?;
                    rename = Some(s.value());
                }
                return Ok(());
            }
            if meta.path.is_ident("default") {
                if meta.input.peek(syn::Token![=]) {
                    let s: LitStr = meta.value()?.parse()?;
                    serde_default = SerdeDefault::Path(syn::parse_str::<syn::Path>(&s.value())?);
                } else {
                    serde_default = SerdeDefault::Implicit;
                }
                return Ok(());
            }
            // Any other serde key: swallow an optional `= value`.
            if meta.input.peek(syn::Token![=]) {
                let _: Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
    }
    Ok((rename, serde_default))
}

/// Read `#[serde(tag = "…")]` on an enum; reject adjacently-tagged (`content`).
fn extract_serde_tag(attrs: &[Attribute]) -> syn::Result<Option<String>> {
    let mut tag = None;
    let mut has_content = false;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("tag") {
                let s: LitStr = meta.value()?.parse()?;
                tag = Some(s.value());
                return Ok(());
            }
            if meta.path.is_ident("content") {
                has_content = true;
                if meta.input.peek(syn::Token![=]) {
                    let _: LitStr = meta.value()?.parse()?;
                }
                return Ok(());
            }
            if meta.input.peek(syn::Token![=]) {
                let _: Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
    }
    if has_content {
        return Err(syn::Error::new(
            Span::call_site(),
            "Buildable does not support adjacently-tagged enums (#[serde(content)]) yet",
        ));
    }
    Ok(tag)
}

fn extract_rename_all(attrs: &[Attribute]) -> syn::Result<Option<String>> {
    let mut out = None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename_all") {
                let s: LitStr = meta.value()?.parse()?;
                out = Some(s.value());
                return Ok(());
            }
            if meta.input.peek(syn::Token![=]) {
                let _: Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
    }
    Ok(out)
}

/// Collect `#[doc = "…"]` lines, joined with newlines and trimmed.
fn extract_doc(attrs: &[Attribute]) -> Option<String> {
    let mut lines = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let Meta::NameValue(nv) = &attr.meta
            && let Expr::Lit(ExprLit {
                lit: Lit::Str(s), ..
            }) = &nv.value
        {
            lines.push(s.value().trim().to_string());
        }
    }
    if lines.is_empty() {
        None
    } else {
        Some(lines.join("\n"))
    }
}

// ---------------------------------------------------------------------------
// Type inspection
// ---------------------------------------------------------------------------

/// Returns `(is_option, inner_or_self)`.
fn unwrap_option(ty: &Type) -> (bool, Type) {
    if let Type::Path(tp) = ty
        && tp.qself.is_none()
        && let Some(seg) = tp.path.segments.last()
        && seg.ident == "Option"
        && let PathArguments::AngleBracketed(ab) = &seg.arguments
        && let Some(GenericArgument::Type(inner)) = ab.args.first()
    {
        return (true, inner.clone());
    }
    (false, ty.clone())
}

/// The `T` of a `Vec<T>`, if `ty` is one.
fn unwrap_vec(ty: &Type) -> Option<Type> {
    if let Type::Path(tp) = ty
        && tp.qself.is_none()
        && let Some(seg) = tp.path.segments.last()
        && seg.ident == "Vec"
        && let PathArguments::AngleBracketed(ab) = &seg.arguments
        && let Some(GenericArgument::Type(inner)) = ab.args.first()
    {
        return Some(inner.clone());
    }
    None
}

fn last_ident(ty: &Type) -> Option<String> {
    if let Type::Path(tp) = ty {
        return tp.path.segments.last().map(|s| s.ident.to_string());
    }
    None
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

fn lit_to_string(lit: &Lit) -> String {
    match lit {
        Lit::Str(s) => s.value(),
        Lit::Bool(b) => b.value.to_string(),
        Lit::Int(i) => i.base10_digits().to_string(),
        Lit::Float(f) => f.base10_digits().to_string(),
        Lit::Char(c) => c.value().to_string(),
        other => quote! { #other }.to_string(),
    }
}

fn opt_str_tokens(value: Option<&str>) -> TokenStream2 {
    match value {
        Some(s) => {
            let lit = LitStr::new(s, Span::call_site());
            quote! { ::core::option::Option::Some(#lit) }
        }
        None => quote! { ::core::option::Option::None },
    }
}

/// Convert an identifier (snake_case field or PascalCase variant) per serde's
/// `rename_all` style.
fn apply_rename_all(ident: &str, style: &str) -> String {
    let words = split_words(ident);
    let lower = || words.iter().map(|w| w.to_lowercase()).collect::<Vec<_>>();
    let upper = || words.iter().map(|w| w.to_uppercase()).collect::<Vec<_>>();
    match style {
        "lowercase" => lower().concat(),
        "UPPERCASE" => upper().concat(),
        "snake_case" => lower().join("_"),
        "SCREAMING_SNAKE_CASE" => upper().join("_"),
        "kebab-case" => lower().join("-"),
        "SCREAMING-KEBAB-CASE" => upper().join("-"),
        "camelCase" => words
            .iter()
            .enumerate()
            .map(|(i, w)| {
                if i == 0 {
                    w.to_lowercase()
                } else {
                    capitalize(w)
                }
            })
            .collect(),
        "PascalCase" => words.iter().map(|w| capitalize(w)).collect(),
        // Unknown style: leave the name as declared.
        _ => ident.to_string(),
    }
}

/// Split an identifier into words on `_`/`-` separators and lower→upper
/// case boundaries (so both `snake_case` and `PascalCase` inputs work).
fn split_words(ident: &str) -> Vec<String> {
    let mut words = Vec::new();
    let mut cur = String::new();
    let mut prev_lower = false;
    for ch in ident.chars() {
        if ch == '_' || ch == '-' {
            if !cur.is_empty() {
                words.push(std::mem::take(&mut cur));
            }
            prev_lower = false;
            continue;
        }
        if ch.is_uppercase() && prev_lower && !cur.is_empty() {
            words.push(std::mem::take(&mut cur));
        }
        cur.push(ch);
        prev_lower = ch.is_lowercase() || ch.is_ascii_digit();
    }
    if !cur.is_empty() {
        words.push(cur);
    }
    words
}

fn capitalize(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
        None => String::new(),
    }
}
