[package]
name = "not-yet-done-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio       = { workspace = true }
async-trait = { workspace = true }
serde       = { workspace = true }
serde_yaml  = { workspace = true }
thiserror   = { workspace = true }
not-yet-done-content = { path = "../not-yet-done-content" }
russh       = "0.61"

[dev-dependencies]
tokio       = { workspace = true }
serde_yaml  = { workspace = true }
