[package]
name = "not-yet-done-sql-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio        = { workspace = true }
async-trait  = { workspace = true }
serde_yaml   = { workspace = true }
not-yet-done-content = { path = "../not-yet-done-content" }

[dev-dependencies]
tokio    = { workspace = true }
tempfile = { workspace = true }
