use not_yet_done_macros::ColumnRegistry;
use sea_orm::entity::prelude::*;
use sea_orm::Set;

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum TaskStatus {
    #[sea_orm(string_value = "todo")]
    Todo,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "done")]
    Done,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, ColumnRegistry)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub description: String,
    pub status: TaskStatus,
    pub deleted: bool,
    pub priority: i32,
    pub parent_id: Option<Uuid>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

// Generated by #[derive(ColumnRegistry)]:
//
// pub struct TaskColumnRegistry;
//
// impl not_yet_done_core::filter::ColumnRegistry for TaskColumnRegistry {
//     fn resolve(&self, _table: Option<&str>, column: &str)
//         -> Option<sea_orm::sea_query::ColumnRef>
//     {
//         use sea_orm::sea_query::IntoColumnRef;
//         match column {
//             "id"          => Some(Column::Id.into_column_ref()),
//             "description" => Some(Column::Description.into_column_ref()),
//             "status"      => Some(Column::Status.into_column_ref()),
//             "deleted"     => Some(Column::Deleted.into_column_ref()),
//             "priority"    => Some(Column::Priority.into_column_ref()),
//             "parent_id"   => Some(Column::ParentId.into_column_ref()),
//             "created_at"  => Some(Column::CreatedAt.into_column_ref()),
//             "updated_at"  => Some(Column::UpdatedAt.into_column_ref()),
//             _             => None,
//         }
//     }
// }

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::new_v4()),
            status: Set(TaskStatus::Todo),
            deleted: Set(false),
            priority: Set(0),
            created_at: Set(chrono::Utc::now()),
            updated_at: Set(chrono::Utc::now()),
            ..ActiveModelTrait::default()
        }
    }
}
